In [1]:
!pip install numpy

In [4]:
import numpy as np

# Create arrays using Numpy

# Create 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
arr2 = np.array([1, 2, 3, 4, 5])

# 1 row and 5 columns
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [13]:
# 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [15]:
# Syntax: np.arange(start, stop, step)
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
# Syntax: np.ones((rows, columns))
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Syntax: np.zeros((rows, columns))
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# Syntax: np.eye(n) -> Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
# Attributes of Numpy Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:", arr.dtype)
print("Item size (in Bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in Bytes): 8


In [35]:
# Numpy vectorize operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9 , 10])

# Element wise addition
print("Addition:", arr1 + arr2)

# Element wise subtraction
print("Subtraction:", arr2 - arr1)

# Element wise multiplication
print("Multiplication:", arr1 * arr2)

# Element wise division
print("Division:", arr1 / arr2)

Addition: [ 7  9 11 13 15]
Subtraction: [5 5 5 5 5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [39]:
# Universal function

arr = np.array([2,3,4,5,6])

# Square root
print("Square root:", np.sqrt(arr))

# Exponential
print("Exponential:", np.exp(arr))

# Sin
print("Sin:", np.sin(arr))

# Natural Log
print("Log:", np.log(arr))

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [48]:
# Array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:\n", arr)
print(arr[0][0])

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [50]:
print(arr[1:,2:])
print(arr[0:2,2:])
print(arr[1:,1:3])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [55]:
# Modify array elements
arr[0,0] = 100
print(arr)

arr[1:] = 69
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [ 69  69  69  69]
 [ 69  69  69  69]]


In [57]:
# Statistical Concept -- Normalization

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [58]:
data = np.array([1, 2, 3, 4, 5])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [69]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5])

print(data[(data>=2) & (data<=4)])

[2 3 4]
