# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [9]:
import numpy as np

# 1. Create a numpy array of shape (5, 5) filled with random integers
arr = np.random.randint(1, 11, size=(5, 5))

arr[:, 3] = 1

print("Modified array:\n", arr)

Modified array:
 [[ 1 10  8  1  6]
 [ 9  2  3  1  8]
 [ 5  7  3  1  7]
 [ 1 10  2  1  7]
 [ 7  6 10  1  7]]


In [10]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.arange(1, 17).reshape((4, 4))

np.fill_diagonal(arr2, 0)
print("Modified array:\n", arr2)

Modified array:
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
# 1. 
arr = np.arange(1, 37).reshape((6, 6))
print("Original Array:\n",arr)

sub_arr = arr[2:6, 1:4]
print("Sub array:\n", sub_arr)


Original Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub array:
 [[14 15 16]
 [20 21 22]
 [26 27 28]
 [32 33 34]]


In [21]:
# 2.
arr2 = np.random.randint(1, 26, size=(5,5))
print("Original Array:\n",arr2)
# extract the elements on the border
border_elements = np.concatenate((arr2[0, :], arr2[-1, :], arr2[1:-1, 0], arr2[1:-1, -1]))

print("Modified Array:\n",border_elements)

Original Array:
 [[ 9 10 21 25  8]
 [24  8 17  8 16]
 [13 17 21  5  8]
 [14 17 16 17  9]
 [13 14 22 23  6]]
Modified Array:
 [ 9 10 21 25  8 13 14 22 23  6 24 13 14 16  8  9]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [27]:
# 1. 
arr1 = np.random.randint(1, 13, size=(3, 4))
arr2 = np.random.randint(13, 25, size=(3, 4))

print(arr,"\n", arr2)

print("Addition:\n", arr1+ arr2)
print("Subtraction:\n", arr1+ arr2)
print("Multiplication:\n", arr1+ arr2)
print("Division:\n", arr1+ arr2)

[[10  8 12  9]
 [ 3  1  6 12]
 [ 2 12  3  3]] 
 [[17 16 18 22]
 [20 20 18 15]
 [20 18 22 16]]
Addition:
 [[24 22 26 32]
 [32 22 28 25]
 [27 30 30 23]]
Subtraction:
 [[24 22 26 32]
 [32 22 28 25]
 [27 30 30 23]]
Multiplication:
 [[24 22 26 32]
 [32 22 28 25]
 [27 30 30 23]]
Division:
 [[24 22 26 32]
 [32 22 28 25]
 [27 30 30 23]]


In [32]:
# 2.
arr3 = np.random.randint(1, 17, size=(4, 4))
row_sum = np.sum(arr3, axis=0)
col_sum = np.sum(arr3, axis=1)
print(row_sum)
print(col_sum)

[23 30 41 40]
[47 17 30 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [40]:
# 1.
arr1 = np.random.randint(1, 26, size=(5, 5))

print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))
print("Variance:", np.var(arr1))

Mean: 14.36
Median: 16.0
Standard Deviation: 6.336434328547878
Variance: 40.1504


In [41]:
# 2.
arr2 = np.arange(1, 10).reshape(3, 3)

mean_arr2 = np.mean(arr2)
std_dev = np.std(arr2)
normalize_arr = arr2 - mean_arr2 /std_dev

print("Normalized array:\n", normalize_arr)

Normalized array:
 [[-0.93649167  0.06350833  1.06350833]
 [ 2.06350833  3.06350833  4.06350833]
 [ 5.06350833  6.06350833  7.06350833]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [45]:
# 1.
arr1 = np.random.randint(1, 10, size=(3,3))
arr2 = np.random.randint(1, 11, size=(3,))
print("2D array:\n", arr1)
print("1D array:",arr2)
result = arr1 + arr2
print("result:\n", arr1+arr2)


2D array:
 [[5 3 4]
 [9 6 9]
 [6 1 8]]
1D array: [1 9 9]
result:
 [[ 6 12 13]
 [10 15 18]
 [ 7 10 17]]


In [49]:
# 2.
arr3 = np.random.randint(1, 17, size=(4, 4))
arr4 = np.random.randint(1, 11, size=(4,))

print("2D array:\n", arr3)
print("1D array:", arr4)

result = arr3 - arr4[:, np.newaxis]
print("Result:\n", result)

2D array:
 [[ 9 11  5 13]
 [ 1  2  7  2]
 [ 9  3 11  7]
 [ 5  6  9 13]]
1D array: [2 4 1 4]
Result:
 [[ 7  9  3 11]
 [-3 -2  3 -2]
 [ 8  2 10  6]
 [ 1  2  5  9]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [51]:
# 1.
arr1 = np.random.randint(1, 10, size=(3, 3))

determinant = np.linalg.det(arr1)
print("Determinant:\n", determinant)

inverse = np.linalg.inv(arr1)
print("Inverse:\n", inverse)

eigenValues = np.linalg.eig(arr1)
print("Eigen Values:\n", eigenValues)

Determinant:
 -197.00000000000017
Inverse:
 [[ 0.29949239 -0.03045685 -0.02538071]
 [-0.11675127 -0.00507614  0.16243655]
 [-0.08121827  0.12690355 -0.06091371]]
Eigen Values:
 EigResult(eigenvalues=array([11.50954904,  3.06849755, -5.57804659]), eigenvectors=array([[ 0.18296375,  0.8316393 , -0.00480777],
       [ 0.79333676, -0.45182008, -0.68369915],
       [ 0.58063848, -0.32285397,  0.72974815]]))


In [55]:
arr2 = np.random.randint(1, 7, size=(2,3))
arr3 = np.random.randint(15, 52, size=(3,2))

# Perform matrix multiplication
result = np.dot(arr2, arr3)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[162 225]
 [190 271]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [57]:
arr1 = np.random.randint(1, 10, size=(3,3))

reshaped_arr1 = arr1.reshape((1, 9))
print("Reshaped array 1:\n", reshaped_arr1)

reshaped_arr2 = arr1.reshape((9, 1))
print("Reshaped array 2:\n", reshaped_arr2)

Reshaped array 1:
 [[9 7 5 5 4 7 7 9 4]]
Reshaped array 2:
 [[9]
 [7]
 [5]
 [5]
 [4]
 [7]
 [7]
 [9]
 [4]]


In [59]:
# 2.
arr2 = np.random.randint(1, 50, size=(5,5))

faltten_arr = arr2.flatten()
print("Flatten arr:\n", faltten_arr)

reshaped_arr = faltten_arr.reshape((5, 5))
print('Reshaped array: \n', reshaped_arr) 


Flatten arr:
 [45 32 13  7 47 35 35 13 38 14 30 31  1 21  2 30 39 31 40 29 18  2 33 28
 44]
Reshaped array: 
 [[45 32 13  7 47]
 [35 35 13 38 14]
 [30 31  1 21  2]
 [30 39 31 40 29]
 [18  2 33 28 44]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [61]:
arr1 = np.random.randint(1, 26, size=(5, 5))
print("Original Array:\n", arr1)

corner_elements = arr1[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner Elements:\n", corner_elements)

Original Array:
 [[ 3 19  6 11  9]
 [ 1 22 24 16 19]
 [22  6 10 13  1]
 [ 6  9 10 13 24]
 [15  8 24 25 14]]
Corner Elements:
 [ 3  9 15 14]


In [63]:
# 2.
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements greater than 10 to 10
array[array > 10] = 10
print("Modified array:")
print(array)

Original array:
[[18 20 15 15]
 [10 20 18 18]
 [12 12  5 19]
 [ 3 15  5  5]]
Modified array:
[[10 10 10 10]
 [10 10 10 10]
 [10 10  5 10]
 [ 3 10  5  5]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [64]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)

print("Original array:")
print(data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [66]:
# 2.
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]
