# 🟡 <font color="Gold">Create array using `numpy`</font>
- Arrays are central to NumPy and provide a foundation for performing mathematical operations and data manipulations.
- The array object in `numpy` called **ndarray**.
### **Syntax** :
```python
import numpy
```

### Aliasing :
- Aliasing refers to giving a shorter or alternative name to a module or a function during import.
- This is done using the **`as`** keyword.

### Why Use Aliasing in Import Statements?
   - Shorten long module names for convenience.
   - Avoid naming conflicts between modules or functions.
   - Improve code readability.
     
### <font color="Cyan">**Syntax**</font> :
#### Importing a Module with an Alias
```python
# Alias 'np' for NumPy
import numpy as np   

# Use 'np' instead of 'numpy'
arr = np.array([1, 2, 3]) 
```

#### Importing Specific Functions with an Alias
```python
# Alias 'sqrt' as 'sq'
from math import sqrt as sq  

# Use 'sq' instead of 'sqrt'
result = sq(16)  
```

---

## 🔶 <font color="OrangeRed">Using `array()`</font> :
- You can **create an array from a list or tuple** using `numpy.array()`.
- The **`numpy.array()`** function in NumPy accepts **lists, tuples, or other numpy arrays** as input to create a new NumPy array.
- The **`numpy.array()`** function does not accept **Set** and **Dictionaries**.
- The elements inside must be of the **same data type** (e.g., integers, floats, or strings).

In [18]:
%config Completer.use_jedi = False
import numpy as np

# Passing a list
x = np.array([1, 2, 3, 4, 5])

# Passing a Tuple
y = np.array((6, 7, 8, 9, 10))

# Passing a list of list (2D Array)
z = np.array([[1, 2], [3, 4]])

print(x)
print(y)
print(z)

print(type(x))   # data type is ndarray

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


---

## 🔶 <font color="Coral">Using `arange()`</font> :
   - Creates an array with a range of numbers.
   - Useful for generating sequences, similar to Python's built-in `range()` but **returns a NumPy array**.

#### Syntax:
```python
    numpy.arange(start, stop, step, dtype=None)
```
   - **Note:** `dtype` is useful when you want to control the memory usuage.
   - You can pass values like `int8`,`int16`, `int32`, `int64`.

In [26]:
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


---

## 🔶 <font color="Coral">Using `linspace()`</font> :
   - Creates an array with evenly spaced numbers over a specified range.
   -  Ideal for generating values between two endpoints, especially when you need a specific number of points.
#### Syntax:
```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

   - **start**: The starting value of the sequence.
   - **stop**: The end value of the sequence.
   - **num** (default 50): The total number of values to generate between start and stop.
   - **endpoint (default True)**: If True, includes stop in the output. If False, excludes stop.
   - **retstep (default False)**: If True, returns a tuple (array, step), where step is the spacing between values.
   - **dtype**: The data type of the output array (e.g., float32, int64).

In [40]:
import numpy as np

arr = np.linspace(0, 10, num=5, dtype=np.int8)

print(arr)

[ 0  2  5  7 10]


---

## 🔶 <font color="Coral">Using `zeros()` and `ones()`</font> :
   - `zeros()` creates an array filled with zeros. It is useful for initializing arrays where all values are initially zero.
   - `ones()` creates an array filled with ones. It is commonly used for creating arrays where all elements start as 1.

#### Syntax:
```python
numpy.zeros(shape, dtype=float, order='C')
numpy.ones(shape, dtype=float, order='C')
```
   - **order (default 'C')**:
        - This specifies the memory layout order.
        - `'C'` (default): **Row-major (C-style) order**.
        - `'F'`: **Column-major (Fortran-style) order**.
        - This is more relevant when dealing with multidimensional arrays.

In [58]:
import numpy as np

# using `zeros()`
arr = np.zeros((2, 3), dtype=int)

# using `ones()`
arr2 = np.ones((4,6), dtype=float)

print(arr)
print(arr2)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


---

## 🔶 <font color="Coral">Using `empty()`</font> :
   - Creates an uninitialized array (values are random).
   - Creates an array without initializing its elements. Faster than `zeros()` or `ones()` but contains garbage values.

#### Syntax:
```python
numpy.empty(shape, dtype=float, order='C')
```

In [73]:
import numpy as np

arr = np.empty((3, 2), dtype=float)
print(arr)  

[[0. 0.]
 [0. 0.]
 [0. 0.]]


---

## 🔶 <font color="Coral">Using `full()`</font> :
  - Creates an array filled with a specified value.
  - Useful for creating arrays with all elements set to a **constant value**.

#### Syntax:
```python
numpy.full(shape, fill_value, dtype=None, order='C')
```

In [77]:
import numpy as np

arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


---

## 🔶 <font color="Coral">Using `eye()`</font> :
   - Creates a 2D identity matrix with ones on the diagonal.
   - Often used in linear algebra for identity matrices.

#### Syntax:
```python
numpy.eye(N, M=None, k=0, dtype=float, order='C')
```
   - `N` is the **number of rows** in the identity matrix.
   - `M` is the **number of columns** in the identity matrix. **If not specified, it is set equal to N, creating a square matrix**.
   - `K` means **The diagonal offset**.
   - `k=0`: The main diagonal (the diagonal from top-left to bottom-right).
   - `k>0`: The diagonal above the main diagonal.
   - `k<0`: The diagonal below the main diagonal.
   - Example: k=1 will shift the diagonal one step up.

In [104]:
import numpy as np

arr = np.eye(3,M=3, dtype=int)

# k = 1 will step up diagonal by 1
arr2 = np.eye(3,M=3, k=1, dtype=int)
              
print(arr)
print(arr2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0 1 0]
 [0 0 1]
 [0 0 0]]


---
---

## 🟢 <font color="MediumSpringGreen">Dimensions in array</font> :
![](https://miro.medium.com/v2/resize:fit:1400/1*m6w9RoOMnWxiQLpCLrY3IA.png)
- In `NumPy`, the **dimension of an array** refers to the **number of axes (or levels of nested arrays)** it has. It is also called the **rank of the array**.

### 🔰 <font color="MediumSpringGreen">**0-D Arrays**</font> :
- It refer to arrays that have **zero dimensions**.
- A **0-dimensional** array is essentially **a scalar**, meaning **it holds a single value**, but it is still treated as an array.

In [40]:
import numpy as np

x = np.array(42)

print(x)
print(type(x))

# The .ndim property returns 0, indicating it's a 0-D array.
print(x.ndim)

# The .shape returns (), confirming it's a single value without any axes.
print(x.shape)

42
<class 'numpy.ndarray'>
0
()


### 🔰 <font color="MediumSpringGreen">**1-D Arrays**</font> :
   - **Definition**: A 1D array (one-dimensional array) is a simple linear array of elements, like a list in Python.
   - **Shape**: The shape of a 1D array is a tuple with a **single value (n,)**, where n is the number of elements in the array.
   - **Indexing**: Elements in a 1D array can be accessed using a single index.
   - **Operations**: You can perform element-wise operations like addition, subtraction, etc., directly on 1D arrays.

In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])  # 1D array

print(arr)    

# returns the dimension and size of the array in a tuple
print("Size of array: ", arr.shape)     

# returns the dimensions of the array
print("Dimensions: ",arr.ndim)    

# Value access
print(arr[0])        

[1 2 3 4 5]
Size of array:  (5,)
Dimensions:  1
1


### 🔰 <font color="MediumSpringGreen">**2-D Arrays**</font> :
   - **Definition**: A 2D array (two-dimensional array) is an array with rows and columns, like a matrix.
   - **Shape**: The ***shape of a 2D array is a tuple (rows, columns)***, where rows is the number of rows and columns is the number of columns.
   - **Indexing**: Elements in a 2D array can be accessed using two indices: one for the row and one for the column.
   - **Operations**: You can perform element-wise operations (like addition, multiplication) on 2D arrays, and operations can be performed along specific axes (rows or columns).

In [61]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape) 
print(arr[0, 1])  # Element in the first row, second column

(2, 3)
2


### 🔰 <font color="MediumSpringGreen">**3-D Arrays**</font> :
   - **Definition**: A 3D array (three-dimensional array) is an array of arrays of arrays, often thought of as a **"stack" of 2D arrays (like a cube)**.
   - **Shape**: The shape of a 3D array is a **`tuple (depth, rows, columns)`**, where:
        - `depth` is the number of 2D arrays (layers),
        - `rows` is the number of rows in each 2D array,
        - `columns` is the number of columns in each 2D array.
   - **Indexing**: Elements in a 3D array are accessed using three indices: one for depth, one for rows, and one for columns.
   - **Operations**: You can perform element-wise operations on a 3D array and also apply operations along any of the three axes (depth, rows, or columns).

In [72]:
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Output: (2, 2, 2) -> 2 depth, 2 rows, 2 columns
print("Size of an array", arr.shape)

# Total number of dimensions in array
print("Dimensions: ", arr.ndim)

# Element in depth 0, row 1, column 1
print(arr[0, 1, 1])

Size of an array (2, 2, 2)
Dimensions:  3
4


### 🔰 <font color="MediumSpringGreen">**Higher Dimensional Arrays**</font> :
- An array can have any number of dimensions.
- When the array is created, you can defined the number of dimensions by using the **`ndmin`** argument.

In [52]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Number of dimensions: ",arr.ndim)
print("Shape of the array: ",arr.shape)

[[[[[1 2 3 4]]]]]
Number of dimensions:  5
Shape of the array:  (1, 1, 1, 1, 4)


---
---

## <font color="red">**Extras**</font>

### ❓ Convert 1-D array to 5-D :

In [76]:
import numpy as np

arr_1to5 = np.array([1,2,3,4,5], ndmin=5)

print(arr_1to5)
print(arr_1to5.ndim)

[[[[[1 2 3 4 5]]]]]
5


---