# 🟡 Slicing in Numpy array
   - **Slicing** refers to extracting a portion (or subset) of an array using the colon **`:`** operator.
   - It allows you to select specific **elements, rows, columns, or sub-arrays from a larger array efficiently**, without copying the data.




---

## ☢️ <font color="orange">Slicing in 1-D array</font>:

#### Syntax: 

 **array[ `start` : `end` : `step` ]**

In [26]:
%config Completer.use_jedi = False

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract elements from index 1 to 4 (exclusive)
print(arr[1:4])

# Extract every second element
print(arr[::2])

# Reverse the array using slicing
print(arr[::-1])

# Negative Slicing
print(arr[-3:])

[2 3 4]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
[ 8  9 10]


## ☢️ <font color="orange">Slicing in 2-D array</font>:
#### <font color="Cyan">**Syntax**</font> : array`[start_row : end_row, start_col : end_col]`
   - **start_row**: The starting row index (inclusive).
   - **end_row**: The ending row index (exclusive).
   - **start_col**: The starting column index (inclusive).
   - **end_col**: The ending column index (exclusive).


In [44]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

# Extract the first row
print("First Row: ", arr[0, :])

# Extract the second column
print("Second Column: ", arr[0:, 1])

First Row:  [10 20 30]
Second Column:  [20 50 80]


## ☢️ <font color="orange">Slicing in 3-D array</font>:
#### <font color="Cyan">**Syntax**</font> : array`[start_depth : end_depth, start_row : end_row, start_col : end_col]` 
   - **start_depth**: Starting index for the depth (inclusive).
   - **end_depth**: Ending index for the depth (exclusive).
   - **start_row**: Starting index for rows (inclusive).
   - **end_row**: Ending index for rows (exclusive).
   - **start_col**: Starting index for columns (inclusive).
   - **end_col**: Ending index for columns (exclusive).

In [8]:
import numpy as np

# Create a 3D array
arr_3d = np.array([
    [[1, 2, 3], 
     [4, 5, 6]],
    [[7, 8, 9], 
     [10, 11, 12]],
    [[13, 14, 15], 
     [16, 17, 18]]
])

print(arr_3d.shape)

print(arr_3d[0, 1, :])

# Extract all rows and columns from the first depth (depth index 0)
print(arr_3d[0, 0:, 0:])

# Extract the first row across all depths
print(arr_3d[0:, 0, 0:])

# Extract the first column across all depths and rows
print(arr_3d[0:, 0:, 0])

(3, 2, 3)
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[ 1  4]
 [ 7 10]
 [13 16]]


---