# 🟡 Numpy array reshaping using `.reshape()`
   - Reshaping is the process of changing the shape or structure of a NumPy array without changing its data.
   - It allows you to rearrange the elements of the array into a different number of rows, columns, or dimensions.
   - **Reshaping does not change the original array; it returns a new array with the new shape**.

In [13]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Array before reshaping: ", arr)

print()

# 2D array
arr_2D = arr.reshape(3, 4)
print("2D array: ")
print(arr_2D)

print()

# 3D array
arr_3D = arr.reshape(2, 2, 3)
print("3D array: ")
print(arr_3D)

Array before reshaping:  [ 1  2  3  4  5  6  7  8  9 10 11 12]

2D array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3D array: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 🔰 Flattening the array from `2D`, `3D` ⟹ `1D`

In [22]:
import numpy as np

# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_2d = arr.reshape(-1)

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
flattened_3d = arr_3d.reshape(-1)

print(flattened_2d)
print(flattened_3d)

[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


## ☢️ `.flatten()` and `.ravel()` :
   - You can  also flatten an array using the `.flatten()` method or the `.ravel()` method.
   - `.flatten()` returns a **copy of the array** as 1D.
   - `.ravel()` returns a **view(reference) of the array** as 1D (if possible).

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using flatten()
arr_flattened = arr.flatten()
arr_flattened[0] = 100
print("Original array after flattening:", arr)  
print("Flattened array:", arr_flattened)  

print()

# Using ravel()
arr_raveled = arr.ravel()
arr_raveled[0] = 200
print("Original array after raveling:", arr)  
print("Raveled array:", arr_raveled)  


Original array after flattening: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array: [100   2   3   4   5   6   7   8   9]

Original array after raveling: [[200   2   3]
 [  4   5   6]
 [  7   8   9]]
Raveled array: [200   2   3   4   5   6   7   8   9]
