# 🟡 Array Joining
   - Joining arrays means combining multiple arrays into one, either along a specific axis (rows or columns).

---

## ⚜️ Using `np.concatenate()` method
   - **Joins existing arrays along an existing axis**.
   - You combine arrays **without adding any new dimensions**.
   - Think of it as extending the rows or columns of a spreadsheet.

### 🔰 `.concatenate()` method on 1-D arrays

In [11]:
import numpy as np

# 1D arrays
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

result = np.concatenate((arr1, arr2))

print(result)

[1 2 3 4]


### 🔰 `.concatenate()` method on 2-D arrays

In [42]:
import numpy as np

# 2D arrays
arr1 = np.array([[1, 2], [45, 46]])
arr2 = np.array([[3, 4], [47, 48]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)

[[ 1  2  3  4]
 [45 46 47 48]]


---
---

## ⚜️ Using `np.stack()` method:
   - Joins arrays along a new axis.
   - Joins arrays along a new axis, adding a new dimension.
   - Think of it as creating a new layer or stack.
   - Useful when you need to keep arrays separate in a new dimension (like stacking paper sheets into a stack).

In [40]:
import numpy as np

arr1 = np.array([1, 2, 5, 6])
arr2 = np.array([3, 4, 7, 8])

result = np.stack((arr1, arr2), axis=1)
print(result)       

[[1 3]
 [2 4]
 [5 7]
 [6 8]]


---
---

## ⚜️ Using `np.hstack()` method:
   - Joins arrays horizontally (along columns)

In [52]:
import numpy as np

arr1 = np.array([1, 2, 5, 6])
arr2 = np.array([3, 4, 7, 8])

result = np.hstack((arr1, arr2))
print(result)

[1 2 5 6 3 4 7 8]


---
---

## ⚜️ Using `np.vstack()` method:
   - Joins arrays vertically (along rows).

In [54]:
import numpy as np

arr1 = np.array([1, 2, 5, 6])
arr2 = np.array([3, 4, 7, 8])

result = np.vstack((arr1, arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


---
---

## ⚜️ Using `np.dstack()` method:
   - Joins arrays along the depth **`(third dimension)`**.

In [63]:
import numpy as np

arr1 = np.array([1, 2, 5, 6])
arr2 = np.array([3, 4, 7, 8])

result = np.dstack((arr1, arr2))
print(result)

[[[1 3]
  [2 4]
  [5 7]
  [6 8]]]
