### Topic to learn
   - Fancy indexing
   - Boolean ind

# 🟡 Scalar Operations 
   - Operate between a NumPy array and a single scalar value (applied to all elements).
- **Addition**: array + scalar
- **Subtraction**: array - scalar
- **Multiplication**: array * scalar
- **Division**: array / scalar
- **Exponentiation**: array ** scalar

In [7]:
import numpy as np

arr = np.array([1, 2, 3])

product = arr * 2
difference = arr - 2
addition = arr + 2
division = arr / 2
exponentiation = arr ** 2

print("Multiplication:", product)
print("Subtraction:", difference)
print("Addition:", addition)
print("Division:", division)
print("exponentiation:", exponentiation)

Multiplication: [2 4 6]
Subtraction: [-1  0  1]
Addition: [3 4 5]
Division: [0.5 1.  1.5]
exponentiation: [1 4 9]


---

# 🟡 Vector Operations (Element-wise) :
   - Operate element-wise between two arrays of the same shape.
- **Addition**: array1 + array2
- **Subtraction**: array1 - array2
- **Multiplication**: array1 * array2
- **Division**: array1 / array2

In [114]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

product = arr1 * arr2
difference = arr1 - arr2
addition = arr1 + arr2
division = arr1 / arr2

print("Multiplication:", product)
print("Subtraction:", difference)
print("Addition:", addition)
print("Division:", division)

Multiplication: [ 4 10 18]
Subtraction: [-3 -3 -3]
Addition: [5 7 9]
Division: [0.25 0.4  0.5 ]


---

# 🟡 Matrix (Dot Product) 
- Calculates the dot product of two arrays.
```python
Dot Product: np.dot(array1, array2) or array1 @ array2

In [30]:
# Dot product of 1D array
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Dot product of 2d array
arr3 = np.array([[1, 2], [3, 4]]) 
arr4 = np.array([[5, 6], [7, 8]]) 

ans_1D = np.dot(arr1, arr2)
ans_2D = np.dot(arr3, arr4)

print("Dot product of 1D array: ",ans_1D)
print(f"Dot product of 2D array: {ans_2D}")

Dot product of 1D array:  11
Dot product of 2D array: [[19 22]
 [43 50]]


# 🟡 Aggregate Operations

- **Sum**: `np.sum(array)`
- **Mean**: `np.mean(array)`
- **Min/Max**: `np.min(array), np.max(array)`
- **Standard Deviation**: `np.std(array)`

In [146]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.median(arr))


21
3.5
6
1
1.707825127659933
3.5


---
---

# 🟡 `numpy.random` function
- The `np.random` module in NumPy is used to generate random numbers, arrays, or perform random sampling.

## 🟩 1. <font color="cyan">`.random()` : Random Numbers</font>

### ♦️ Single Random Number (0 to 1):
- Generate a random float between 0 and 1

In [57]:
import numpy as np
print(np.random.random())

0.3701324181046576


### ♦️ Array of Random Numbers (0 to 1):

In [64]:
import numpy as np

# Generate the array of shape (2,3) with random values inside it
arr = np.random.random((2, 3))

print(arr)

[[0.79727213 0.18329031 0.95445202]
 [0.46568672 0.31320012 0.83522737]]


## 🟩 2. <font color="cyan">`.randint()` : Integers</font>

### ♦️ Random Integers in a Range:

In [72]:
import numpy as np

# Random integer from 1 to 9
print(np.random.randint(1, 10))  

2


### ♦️ Array of Random Integers:

In [76]:
import numpy as np

# 2x3 array of integers
print(np.random.randint(1, 10, size=(2, 3)))  

[[9 2 8]
 [5 1 2]]


## 🟩 3. <font color="cyan">`.choice()` : Random Sampling</font>

### ♦️ Random Choice from a List:

In [86]:
import numpy as np

# Randomly picks one element
print(np.random.choice([1, 2, 3, 4, 5]))

2


### ♦️ Random Choice with Replacement:
- Random Choice with Replacement in NumPy allows you to randomly select elements from a list or array with repetition allowed. This means the same element can be chosen multiple times.

In [93]:
import numpy as np

# Allows repeats
print(np.random.choice([1, 2, 3], size=6, replace=True))

[1 3 1 1 2 2]


### ♦️ Random Choice Without Replacement:

In [104]:
import numpy as np

# No repeats
print(np.random.choice([1, 2, 3], size=3, replace=False))  

[2 1 3]


---
---

# 🟡 Mathematical Operations

## 🔰 Basic Arithmetic Operations :

In [121]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# addition
addition = np.add(arr1, arr2)  # or arr1 + arr2

# subtraction
subtraction = np.subtract(arr1, arr2)  # or arr1 - arr2

# Multiplication
multiplication = np.multiply(arr1, arr2)  # or arr1 * arr2

# Division
division = np.divide(arr1, arr2)  # or arr1 / arr2

# Exponentiation
exponentiation= np.power(arr1, 2)  # or arr1 ** 2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)
print("Exponentiation:", exponentiation)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Exponentiation: [1 4 9]


## 🔰 Trigonometric Functions :

In [130]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi])

# sine
sine = np.sin(arr)

# cosine
cosine = np.cos(arr)

print("Sine: ", sine)
print("cosine: ", cosine)

Sine:  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cosine:  [ 1.000000e+00  6.123234e-17 -1.000000e+00]


## 🔰 Exponential and Logarithmic Functions

In [135]:
import numpy as np

arr = np.array([1, 2, 3])

# Exponential (e^x)
exponential = np.exp(arr)

# Natural Logarithm (log_e)
natural_log = np.log(arr)

# Logarithm Base 10
log_10 = np.log10(arr)

print("Exponential:", exponential)
print("Natural Log:", natural_log)
print("Log Base 10:", log_10)

Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Log: [0.         0.69314718 1.09861229]
Log Base 10: [0.         0.30103    0.47712125]


## 🔰 Power and Roots

In [144]:
import numpy as np

arr = [1, 2, 3]

# Square of a number
square_root = np.sqrt(arr)

# Cube root
cube_root = np.cbrt(arr)

# N-th Root
n = 4
nth_root = np.power(arr, 1/n)

print("Square root:", square_root)
print("Cube root:", cube_root)
print(f"{n}-th root:", nth_root)

Square root: [1.         1.41421356 1.73205081]
Cube root: [1.         1.25992105 1.44224957]
4-th root: [1.         1.18920712 1.31607401]


---

## 🔰 Other Mathematical Functions

### ⏺ Absolute value : `.abs()`

In [153]:
import numpy as np

arr = np.array([-1, -2, 3])

result = np.abs(arr)
print("Absolute Value:", result)

Absolute Value: [1 2 3]


### ⏺ Floor (round down) : `.floor()`

In [14]:
import numpy as np

arr = np.array([1.9, 2.5, 3.7])

result = np.floor(arr)
print("Floor:", result)

Floor: [1. 2. 3.]


### ⏺ Ceiling (round up) :  `.ceil()`

In [16]:
import numpy as np

arr = np.array([1.9, 2.5, 3.7])

result = np.ceil(arr)
print("Ceiling:", result)

Ceiling: [2. 3. 4.]


### ⏺ Rounding to the nearest integer : `.round()`

In [18]:
import numpy as np

arr = np.array([1.9, 2.3, 3.7])

result = np.round(arr)
print("Rounded:", result)  

Rounded: [2. 2. 4.]


---
---

# 🟡 Array Manipulation Methods

### 🟩 `.unique()` : To find the unique elements of an array 

### Syntax:
```python
numpy.unique(arr, axis=None, return_index=False, return_inverse=False, return_counts=False, sort=True)
```

In [43]:
import numpy as np

arr = np.array([4, 2, 2, 3, 3, 4, 5])

# Find unique values
unique_vals = np.unique(arr)
print("Unique values:", unique_vals) 

print()

# Return unique values with indices of first occurrences
unique_vals, indices = np.unique(arr, return_index=True)
print("Unique values:", unique_vals)  
print("Indices of first occurrences:", indices)  

print()

# Return unique values with counts of occurrences
unique_vals, counts = np.unique(arr, return_counts=True)
print("Unique values:", unique_vals)  
print("Counts:", counts)  

Unique values: [2 3 4 5]

Unique values: [2 3 4 5]
Indices of first occurrences: [1 3 0 6]

Unique values: [2 3 4 5]
Counts: [2 2 2 1]


### 🟩 `.delete()` : To delete elements from an array

#### Syntax:
```python
numpy.delete(arr, obj, axis=None)
```
#### **Parameters**:
   - **arr**: The input array from which elements will be deleted.
   - **obj**: The index or indices of the elements to delete. Can be a single index, a list/array of indices, or a slice.
   - **axis (optional)**: The axis along which to delete. If None (default), the array is flattened before deletion. If an axis is specified, elements are deleted along that axis.

### ♦️ Deleting Elements by Index

In [73]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

# Delete element at index 2 (the element '3')
arr_deleted = np.delete(arr, 2)  

print(arr_deleted)  

[1 2 4 5]


### ♦️ Deleting Multiple Elements by Indices

In [65]:
arr = np.array([1, 2, 3, 4, 5])

# Delete elements at indices 1 and 3 (elements '2' and '4')
arr_deleted = np.delete(arr, [1, 3])  
print(arr_deleted)  

[1 3 5]


### ♦️ Deleting Elements along a Specific Axis (2D Array)

In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete the second row (index 1)
arr_deleted = np.delete(arr, 1, axis=0)  
print(arr_deleted)

print()

# Delete the second column (index 1)
arr_deleted = np.delete(arr, 1, axis=1)  
print(arr_deleted)

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]
