# 🟡 Searching NumPy Array
![](https://www.askpython.com/wp-content/uploads/2021/03/SeaRch-operation-in-numpy-1024x512.png)
- Searching in NumPy arrays **helps locate specific elements or values meeting conditions**.
- It is essential for **filtering and analyzing data in arrays**.
- Makes data processing faster and more efficient compared to regular Python lists.
-  A key feature of NumPy that **simplifies working with numerical data**.
-  By understanding how to search within arrays, users can handle large datasets more effectively, making NumPy an essential library for data processing tasks.

> <font color="Yellow">**You can search an array for a certain value and it will return the indexes that get the match by using `where()`.**</font>

---
---

## ⚜️ Using `np.where()` :
- Always remember, **it returns indices where a condition is true**.

#### Syntax :
```python
np.where(condition)
```

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 3)

print(indices)

(array([3, 4], dtype=int64),)


---

## ⚜️ Using **Boolean Indexing** :
- ***Boolean indexing*** **allows you to filter or retrieve elements from an array** based on conditions.
-  It enables you to perform operations on specific elements without using loops.

#### Syntax :
```python
filtered_array = array[condition]
```

> <font color="Yellow">**This method returns elements after filteration and not indices.**</font>

### 🔰 <font color="Yellow">Basic Example</font> :

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
filtered = arr[arr > 3]

print(filtered)

[4 5]


### 🔰 <font color="Yellow">Multiple Condition</font> :
- Use `&` **(AND)**, `|` **(OR)**, and `~` **(NOT)** for combining conditions.
- **Parentheses are required because of operator precedence**.

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
filtered = arr[(arr > 2) & (arr < 5)]

print(filtered)

[3 4]


### 🔰 <font color="Yellow">Using `~` (**NOT** Operator)</font> :
-  The ~ operator inverts the Boolean array.

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

filtered = arr[~(arr > 3)]
print(filtered)  

[1 2 3]


### 🔰 <font color="Yellow">Set Specific Values</font> :
- It modifies the original array.

In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr[arr < 3] = 0

print(arr)

[0 0 3 4 5]


### 🔰 <font color="Yellow">Boolean indexing 2D Arrays</font> :
- Boolean indexing works element-wise in multidimensional arrays.

In [50]:
import numpy as np

arr2d = np.array([[1, 2], [3, 4], [5, 6]])

filtered = arr2d[arr2d > 3]
print(filtered)

[4 5 6]


---

## ⚜️ Using `np.isin()` :
- `np.isin()` function is used to checks ***if elements of an array exist in another array***.
- It ***returns a Boolean array of the same shape as the input array***, where each element indicates if it exists in the specified set of values.

#### Syntax :
```python
numpy.isin(element, test_elements, assume_unique=False, invert=False)
```

#### Parameters :
- **element** : Input array or scalar whose elements will be tested for memebership.
- **test_elements** : The values to be check. Can be a list, array, or scalar.

### 🔰 <font color="Yellow">Basic usage :

In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
test_values = [2, 4, 6]

result = np.isin(arr, test_values)
print(result) 

[False  True False  True False]


### 🔰 <font color="Yellow">Filtering Elements</font> :

In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
test_values = [2, 4, 6]

filtered = arr[np.isin(arr, test_values)]
print(filtered)

[2 4]


### 🔰 <font color="Yellow">With Multidimensional Arrays</font> :

In [70]:
arr2d = np.array([[1, 2], [3, 4], [5, 6]])

test_values = [2, 5]
result = np.isin(arr2d, test_values)

print(result)

[[False  True]
 [False False]
 [ True False]]


---

## ⚜️ Using `np.nonzero()` :
- The **`np.nonzero()`** function is used to find the indices of elements that are non-zero (i.e., elements that are not equal to zero or False) in an array.
- It returns **a tuple of arrays** where each array contains the indices of those elements which are **non-zero** value.

#### Syntax :
```python
# a is an input array
numpy.nonzero(a)
```

### 🔰 <font color="Yellow">Basic Usage (1D Array)</font> :

In [81]:
import numpy as np

arr = np.array([0, 2, 0, 3, 0, 4])
result = np.nonzero(arr)

print(result)

(array([1, 3, 5], dtype=int64),)


### 🔰 <font color="Yellow">Using with 2D Arrays</font> :

In [87]:
import numpy as np

arr2d = np.array([[0, 1, 0], [2, 0, 3], [4, 0, 5]])

result = np.nonzero(arr2d)
print(result)

# Explanation: Returns two arrays representing the row and column indices 
# of non-zero elements:

# The non-zero elements are at (0,1), (1,0), (1,2), (2,0), and (2,2).

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 0, 2, 0, 2], dtype=int64))


### 🔰 <font color="Yellow">Using with `True`/`False` Values</font> :

In [91]:
arr = np.array([True, False, True, False])

result = np.nonzero(arr)
print(result)

(array([0, 2], dtype=int64),)


---

## ⚜️ Using `np.argmax()` and `np.argmin()` :
- Finds the **index of the maximum or minimum element**.

In [96]:
import numpy as np

arr = np.array([10, 20, 15, 5])

max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Index of Maximum element:", max_index)
print("Index of Minimum element:", min_index)

Index of Maximum element: 1
Index of Minimum element: 3


---

## ⚜️ Using `np.searchsorted()` :
- Finds the indices where elements should be inserted into a sorted array to maintain order.
- The input array a must be sorted (either in ascending or descending order).

#### Syntax :
```python
numpy.searchsorted(a, v, side='left', sorter=None)
```

#### Parameters :
- **a** : Sorted 1D array
- **v** : Array of values to be inserted
- **`side`** (optional):
    - **`left`** (default) – Insert before the existing element.
    - **`right`** – Insert after the existing element.

#### Returns :
- returs the indices of insertion points for the elements in **`v`**

### 🔰 <font color="Yellow">Basic Usage</font> :

In [117]:
import numpy as np
arr = np.array([1, 3, 5, 7])

index = np.searchsorted(arr, 4)
print(index)

2


### 🔰 <font color="Yellow">Using `side='right'`</font> :

In [127]:
import numpy as np

arr = np.array([1, 3, 5, 7])

index = np.searchsorted(arr, 5, side='right')
print(index)

3


### 🔰 <font color="Yellow">Multiple Values</font> :

In [125]:
import numpy as np

arr = np.array([1, 3, 5, 7])
indices = np.searchsorted(arr, [2, 4, 6])

print(indices)

[1 2 3]


---