# 🟡 Sorting in NumPy Array
- Use **`numpy.sort()`** to sort an array.
- **Does not modify the original array** (returns a sorted copy).
- Default is **ascending order**.

---

## 🟢 <font color="LightGreen">Basic Sorting</font> :
- `numpy.sort()` sorts the array and **returns a new sorted array**.
- Default is ascending order.

In [5]:
import numpy as np

arr = np.array([5,0,8,6,4])
sorted_arr = np.sort(arr)

print(sorted_arr)

[0 4 5 6 8]


---

## 🟢 <font color="LightGreen">Sorting Along Axes</font> :
- **`axis=0`** : Sorts along columns (**vertically**).
- **`axis=1`** : Sorts along rows (**horizontally**).
- **`axis=None`** : Flattens the array before sorting.

In [16]:
import numpy as np

arr = np.array([[3, 5, 2], [6, 1, 4]])

# Sort along columns
sorted_by_col = np.sort(arr, axis=0)
print(sorted_by_col)

# Sort along rows
sorted_by_row = np.sort(arr, axis=1)
print(sorted_by_row)

# Flatten and sort
sorted_flattened = np.sort(arr, axis=None)
print(sorted_flattened)

[[3 1 2]
 [6 5 4]]
[[2 3 5]
 [1 4 6]]
[1 2 3 4 5 6]


---

## 🟢 <font color="LightGreen">In place Sorting</font> :
- To sort the array in place (modifies the original array).

In [21]:
import numpy as np

arr = np.array([3, 1, 2])
arr.sort() 

print(arr)

[1 2 3]


---

## 🟢 <font color="LightGreen">Custom Sorting Algorithms</font> :
- Specify sorting algorithm with the **`kind`** parameter:
     - `quicksort` (default), `mergesort`, `heapsort`, `stable`.

In [25]:
import numpy as np

arr = np.array([3, 1, 2])

# Sort using heapsort
sorted_arr = np.sort(arr, kind='heapsort')  # [1, 2, 3]

print(sorted_arr)

[1 2 3]
